
MAIN_TEXFILE   := paper.tex

OTHER_TEXFILES := macros.tex abstract.tex intro.tex relatedwork.tex semantics.tex splitting.tex example.tex algoexamples.tex figures/*.tex

TEXMACRO_FILE  := 

SPELL          :=   $(addsuffix .spell,  $(MAIN_TEXFILE) $(OTHER_TEXFILES))

BIBFILE        := paper.bib

include common.mk

