
MAIN_TEXFILE   := paper.tex

OTHER_TEXFILES := macros.tex abstract.tex intro.tex overview.tex semantics.tex splitting.tex implementation.tex examples.tex relatedwork.tex conclusion.tex appendix.tex figures/*.tex

TEXMACRO_FILE  := 

SPELL          :=   $(addsuffix .spell,  $(MAIN_TEXFILE) $(OTHER_TEXFILES))

BIBFILE        := paper.bib

include common.mk

